version: '3.8'

services:
  # The Brain
  backend:
    build: ./backend
    container_name: aynovax-core
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost

  # The Face
  frontend:
    build: ./frontend
    container_name: aynovax-ui
    ports:
      - "3000:80" # Maps port 80 inside container to 3000 on your machine
    depends_on:
      - backend